import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';

const BOOKS=[['Genesis',50,'genesis'],['Exodus',40,'exodus'],['Leviticus',27,'leviticus'],['Numbers',36,'numbers'],['Deuteronomy',34,'deuteronomy'],['Joshua',24,'joshua'],['Judges',21,'judges'],['Ruth',4,'ruth'],['1 Samuel',31,'1samuel'],['2 Samuel',24,'2samuel'],['1 Kings',22,'1kings'],['2 Kings',25,'2kings'],['1 Chronicles',29,'1chronicles'],['2 Chronicles',36,'2chronicles'],['Ezra',10,'ezra'],['Nehemiah',13,'nehemiah'],['Esther',10,'esther'],['Job',42,'job'],['Psalms',150,'psalms'],['Proverbs',31,'proverbs'],['Ecclesiastes',12,'ecclesiastes'],['Song of Solomon',8,'songofsolomon'],['Isaiah',66,'isaiah'],['Jeremiah',52,'jeremiah'],['Lamentations',5,'lamentations'],['Ezekiel',48,'ezekiel'],['Daniel',12,'daniel'],['Hosea',14,'hosea'],['Joel',3,'joel'],['Amos',9,'amos'],['Obadiah',1,'obadiah'],['Jonah',4,'jonah'],['Micah',7,'micah'],['Nahum',3,'nahum'],['Habakkuk',3,'habakkuk'],['Zephaniah',3,'zephaniah'],['Haggai',2,'haggai'],['Zechariah',14,'zechariah'],['Malachi',4,'malachi'],['Matthew',28,'matthew'],['Mark',16,'mark'],['Luke',24,'luke'],['John',21,'john'],['Acts',28,'acts'],['Romans',16,'romans'],['1 Corinthians',16,'1corinthians'],['2 Corinthians',13,'2corinthians'],['Galatians',6,'galatians'],['Ephesians',6,'ephesians'],['Philippians',4,'philippians'],['Colossians',4,'colossians'],['1 Thessalonians',5,'1thessalonians'],['2 Thessalonians',3,'2thessalonians'],['1 Timothy',6,'1timothy'],['2 Timothy',4,'2timothy'],['Titus',3,'titus'],['Philemon',1,'philemon'],['Hebrews',13,'hebrews'],['James',5,'james'],['1 Peter',5,'1peter'],['2 Peter',3,'2peter'],['1 John',5,'1john'],['2 John',1,'2john'],['3 John',1,'3john'],['Jude',1,'jude'],['Revelation',22,'revelation']];
const TOPICS=['Faith','Prayer','Forgiveness','Purity','Love','Marriage','Family','Wisdom','Fear','Hope','Healing',"God's Character",'Holy Spirit','Jesus','Salvation','Sin','Repentance','Obedience','Purpose','Calling','Work','Money','Leadership','Friendship','Discipline','Temptation','Trials','Suffering','Peace','Joy','Gratitude','Worship','Fasting','Waiting on God','Courage','Identity','Spiritual Growth'];
const TOPIC_REFS={Faith:['Genesis 15:6','Proverbs 3:5–6','Habakkuk 2:4','Matthew 17:20','Romans 10:17','Hebrews 11:1–6'],Prayer:['1 Samuel 1:10–18','Psalm 5:1–3','Matthew 6:5–13','Luke 11:1–13','Philippians 4:6–7','1 Thessalonians 5:17'],Forgiveness:['Genesis 50:15–21','Matthew 6:14–15','Matthew 18:21–35','Luke 23:34','Ephesians 4:31–32','Colossians 3:12–13'],Purity:['Psalm 119:9–11','Matthew 5:27–30','1 Corinthians 6:18–20','2 Timothy 2:22','1 Thessalonians 4:3–5'],Love:['Leviticus 19:18','John 13:34–35','1 Corinthians 13:1–13','1 John 4:7–12'],Marriage:['Genesis 2:18–25','Matthew 19:4–6','Ephesians 5:21–33','Hebrews 13:4'],Family:['Genesis 18:17–19','Deuteronomy 6:4–9','Psalm 127:3–5','Ephesians 6:1–4'],Wisdom:['Proverbs 1:1–7','Proverbs 3:13–18','James 1:5','James 3:13–18'],Fear:['Psalm 23:4','Psalm 56:3–4','Isaiah 41:10','2 Timothy 1:7'],Hope:['Psalm 42:5','Isaiah 40:31','Romans 5:1–5','Romans 15:13'],Healing:['Psalm 103:1–5','Isaiah 53:4–5','Jeremiah 17:14','James 5:14–16'],Salvation:['Isaiah 45:22','John 3:16–18','Acts 4:12','Romans 10:9–13','Ephesians 2:8–10'],Sin:['Genesis 3:1–24','Psalm 51:1–17','Romans 3:23','Romans 6:23','1 John 1:8–9'],Repentance:['2 Chronicles 7:14','Psalm 51:10–13','Mark 1:14–15','Acts 3:19'],Obedience:['Deuteronomy 10:12–13','1 Samuel 15:22','John 14:15','James 1:22–25'],Purpose:['Esther 4:14','Jeremiah 29:11','Romans 8:28','Ephesians 2:10'],Work:['Genesis 2:15','Proverbs 14:23','Colossians 3:23–24'],Money:['Deuteronomy 8:18','Proverbs 11:24–25','Matthew 6:19–24','1 Timothy 6:6–10','Hebrews 13:5'],Leadership:['Exodus 18:17–23','Joshua 1:6–9','Mark 10:42–45','1 Timothy 3:1–13'],Friendship:['1 Samuel 18:1–4','Proverbs 17:17','Proverbs 27:17','John 15:13–15'],Discipline:['Proverbs 12:1','Proverbs 25:28','Hebrews 12:5–11'],Temptation:['Genesis 39:7–12','Matthew 4:1–11','1 Corinthians 10:13','James 1:12–16'],Trials:['Job 1:20–22','Psalm 34:17–19','James 1:2–4','1 Peter 1:6–7'],Suffering:['Psalm 34:18','Romans 8:18','2 Corinthians 4:16–18','1 Peter 5:10'],Peace:['Psalm 4:8','Isaiah 26:3','John 14:27','Philippians 4:6–9'],Joy:['Nehemiah 8:10','Psalm 16:11','John 15:11','Philippians 4:4'],Gratitude:['Psalm 100:1–5','Psalm 107:1','Colossians 3:15–17','1 Thessalonians 5:18'],Worship:['Psalm 95:1–7','Psalm 150:1–6','John 4:23–24','Romans 12:1'],Fasting:['Judges 20:26','Ezra 8:21–23','Matthew 6:16–18','Acts 13:2–3'],Courage:['Joshua 1:9','Psalm 27:1','Daniel 3:16–18','Acts 4:29–31'],Identity:['Genesis 1:26–27','Psalm 139:13–18','2 Corinthians 5:17','1 Peter 2:9'],Spiritual Growth:['Psalm 1:1–3','John 15:1–8','Ephesians 4:11–16','2 Peter 3:18']};
const RANGES=[[1,50],[51,100],[101,150],[151,200],[201,250],[251,300],[301,350],[351,365]];
const KEY='bj-';const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(KEY+k))??d}catch{return d}};const put=(k,v)=>localStorage.setItem(KEY+k,JSON.stringify(v));
const slug=n=>BOOKS.find(b=>b[0].toLowerCase()===n.toLowerCase())?.[2];
const refs=s=>(s||'').split(/;\s*/).map(x=>{x=x.replace('✦','').trim();let m=x.match(/^(.+?)\s+(\d+):(\d+)(?:[–-](\d+))?$/);return m?{book:m[1],chapter:+m[2],start:+m[3],end:+(m[4]||m[3])}:null}).filter(Boolean);
function App(){const[screen,setScreen]=useState('home'),[day,setDay]=useState(get('day',1)),[plan,setPlan]=useState([]),[loaded,setLoaded]=useState({}),[book,setBook]=useState(get('book','Genesis')),[chapter,setChapter]=useState(get('chapter',1)),[done,setDone]=useState(get('done',[])),[daily,setDaily]=useState(get('daily',{})),[notes,setNotes]=useState(get('notes',{})),[prayers,setPrayers]=useState(get('prayers',[])),[saved,setSaved]=useState(get('saved',[])),[marks,setMarks]=useState(get('marks',{})),[q,setQ]=useState(''),[results,setResults]=useState([]),[topic,setTopic]=useState(null),[topicResults,setTopicResults]=useState([]),[loading,setLoading]=useState(false),[menu,setMenu]=useState(false);
useEffect(()=>put('day',day),[day]);useEffect(()=>{put('book',book);put('chapter',chapter)},[book,chapter]);useEffect(()=>put('done',done),[done]);useEffect(()=>put('daily',daily),[daily]);useEffect(()=>put('notes',notes),[notes]);useEffect(()=>put('prayers',prayers),[prayers]);useEffect(()=>put('saved',saved),[saved]);useEffect(()=>put('marks',marks),[marks]);
useEffect(()=>{fetch(import.meta.env.BASE_URL+'data/reading-plan.json').then(r=>r.json()).then(x=>setPlan(x.days||[]))},[]);
const load=async n=>{let s=slug(n);if(!s)return null;if(loaded[s])return loaded[s];try{let r=await fetch(import.meta.env.BASE_URL+'data/web/'+s+'.json');let d=await r.json();setLoaded(x=>({...x,[s]:d}));return d}catch{return null}};
const open=(b,c=1)=>{setBook(b);setChapter(c);setScreen('bible');window.scrollTo({top:0,behavior:'smooth'})};
const journey=plan[day-1];const complete=()=>setDone(x=>x.includes(day)?x.filter(n=>n!==day):[...x,day].sort((a,b)=>a-b));const saveDaily=(f,v)=>setDaily(x=>({...x,[day]:{...(x[day]||{}),[f]:v}}));const saveNote=(f,v)=>setNotes(x=>({...x,[book+' '+chapter]:{...(x[book+' '+chapter]||{}),[f]:v}}));const data=loaded[slug(book)],verses=data?.chapters?.[chapter]||[];
const goDay=n=>{if(n>=1&&n<=365){setDay(n);setScreen('journey');window.scrollTo({top:0,behavior:'smooth'})}};
async function search(){if(!q.trim())return;setLoading(true);let out=[];let exact=q.match(/^(.+?)\s+(\d+):(\d+)$/);if(exact){let d=await load(exact[1]);out=(d?.chapters?.[exact[2]]||[]).filter(v=>v.v===+exact[3]).map(v=>({ref:exact[1]+' '+exact[2]+':'+v.v,text:v.text,book:exact[1],chapter:+exact[2]}))}else{let all=await Promise.all(BOOKS.map(b=>load(b[0])));for(let i=0;i<BOOKS.length&&out.length<60;i++){let d=all[i];for(const[c,vs]of Object.entries(d?.chapters||{})){for(const v of vs){if(v.text.toLowerCase().includes(q.toLowerCase())){out.push({ref:BOOKS[i][0]+' '+c+':'+v.v,text:v.text,book:BOOKS[i][0],chapter:+c});if(out.length>=60)break}}if(out.length>=60)break}}}setResults(out);setLoading(false);setScreen('search')}
async function showTopic(t){setTopic(t);setLoading(true);let out=[];const rlist=TOPIC_REFS[t]||[];for(const r of rlist){let p=refs(r)[0],d=await load(p.book);let vs=(d?.chapters?.[p.chapter]||[]).filter(v=>v.v>=p.start&&v.v<=p.end);out.push({ref:r,text:vs.map(v=>v.text).join(' '),book:p.book,chapter:p.chapter})}setTopicResults(out);setLoading(false)}
return <div className="app"><header className="topbar"><button className="brand" onClick={()=>setScreen('home')}><span className="brand-mark">✦</span><span><b>BIBLE</b><em>JOURNAL</em></span></button><div className="top-actions"><button className="ghost" onClick={()=>setScreen('bible')}>Bible</button><button className="ghost" onClick={()=>setScreen('journey')}>Journey</button><button className="search-button" onClick={()=>setScreen('search')}>⌕ Search</button><button className="menu-btn" onClick={()=>setMenu(!menu)}>☰</button></div></header>{menu&&<div className="mobile-menu"><button onClick={()=>{setScreen('home');setMenu(false)}}>Home</button><button onClick={()=>{setScreen('bible');setMenu(false)}}>Bible Library</button><button onClick={()=>{setScreen('journey');setMenu(false)}}>365-Day Journey</button><button onClick={()=>{setScreen('topics');setMenu(false)}}>Topics</button><button onClick={()=>{setScreen('journal');setMenu(false)}}>Prayer Journal</button><button onClick={()=>{setScreen('bookmarks');setMenu(false)}}>Bookmarks</button></div>}<main>
{screen==='home'&&<Home day={day}done={done.length}setScreen={setScreen}goDay={goDay}/>}
{screen==='journey'&&journey&&<Journey j={journey}day={day}done={done}complete={complete}notes={daily[day]||{}}save={saveDaily}load={load}goDay={goDay}/>}
{screen==='bible'&&<Bible book={book}chapter={chapter}setBook={setBook}setChapter={setChapter}data={data}verses={verses}books={BOOKS}open={open}saved={saved}setSaved={setSaved}marks={marks}setMarks={setMarks}notes={notes[book+' '+chapter]||{}}saveNote={saveNote}setScreen={setScreen}loading={loading}load={load}/>}
{screen==='topics'&&<Topics topic={topic}results={topicResults}show={showTopic}open={open}setTopic={setTopic}loading={loading}/>}
{screen==='journal'&&<Journal prayers={prayers}setPrayers={setPrayers}/>}
{screen==='bookmarks'&&<Bookmarks saved={saved}marks={marks}open={open}/>}
{screen==='search'&&<Search q={q}setQ={setQ}search={search}results={results}open={open}loading={loading}/>}
</main><nav className="bottom-nav"><button onClick={()=>setScreen('home')}>⌂<span>Home</span></button><button onClick={()=>setScreen('bible')}>▤<span>Bible</span></button><button onClick={()=>setScreen('journey')}>◷<span>Journey</span></button><button onClick={()=>setScreen('topics')}>✦<span>Topics</span></button><button onClick={()=>setScreen('journal')}>✎<span>Journal</span></button></nav></div>}

function Home({day,done,setScreen,goDay}){const[typed,setTyped]=useState('');return <section className="hero-page"><div className="hero-copy"><p className="eyebrow">READ · REFLECT · PRAY · GROW</p><h1>Your Bible.<br/><i>Your journal.</i></h1><p className="lead">A peaceful, modern Bible study space with the complete World English Bible and a structured 365-day journey.</p><div className="home-actions"><button className="primary" onClick={()=>setScreen('journey')}>Continue Day {day} →</button><button className="secondary" onClick={()=>setScreen('bible')}>Open Bible</button></div><div className="feature-row"><span>66 books</span><span>365 days</span><span>WEB public-domain text</span><span>Personal notes</span></div></div><div className="dashboard-card"><div className="card-label">365-DAY JOURNEY</div><div className="day-big">Day {day}</div><div className="progress-track"><span style={{width:(done/365*100)+'%'}}/></div><div className="progress-meta"><span>{done} days complete</span><span>{Math.round(done/365*100)}%</span></div><div className="quick-jump"><label>JUMP TO DAY</label><div className="range-row">{RANGES.map(r=><button key={r[0]} onClick={()=>goDay(r[0])}>Days {r[0]}–{r[1]}</button>)}</div><div className="jump-row"><input value={typed} onChange={e=>setTyped(e.target.value.replace(/\D/g,''))} onKeyDown={e=>e.key==='Enter'&&goDay(+typed)} placeholder="Type day number" inputMode="numeric"/><button onClick={()=>goDay(+typed)}>GO</button></div></div><div className="home-cards"><button onClick={()=>setScreen('topics')}>Study by topic <b>→</b></button><button onClick={()=>setScreen('journal')}>Prayer journal <b>→</b></button><button onClick={()=>setScreen('bookmarks')}>My bookmarks <b>→</b></button></div></div></section>}

function Journey({j,day,done,complete,notes,save,load,goDay}){const[blocks,setBlocks]=useState([]);const[busy,setBusy]=useState(true);useEffect(()=>{(async()=>{setBusy(true);let a=[];for(const r of [...refs(j.coreReading),...refs(j.supportingReading)]){let d=await load(r.book);a.push({...r,verses:(d?.chapters?.[r.chapter]||[]).filter(v=>v.v>=r.start&&v.v<=r.end)})}setBlocks(a);setBusy(false)})()},[day,j.coreReading,j.supportingReading]);return <section className="content-page"><div className="section-head"><div><p className="eyebrow">365-DAY JOURNEY</p><h2>Day {day}</h2><p className="muted">{j.title}</p></div><button className={done.includes(day)?'complete done':'complete'} onClick={complete}>{done.includes(day)?'✓ Completed':'Mark as complete'}</button></div><div className="day-nav"><button disabled={day===1} onClick={()=>goDay(day-1)}>← Previous</button><span>Day {day} of 365</span><button disabled={day===365} onClick={()=>goDay(day+1)}>Next →</button></div><article className="journal-card"><div className="reading-meta"><span>CORE READING</span><b>{j.coreReading}</b></div><div className="reading-meta"><span>SUPPORTING</span><b>{j.supportingReading}</b></div><div className="reading-meta"><span>STUDY METHOD</span><b>{j.studyMethod}</b></div><div className="scripture-box"><div className="box-title">TODAY'S SCRIPTURE — WORLD ENGLISH BIBLE</div>{busy?<p className="muted">Loading today's Scripture…</p>:blocks.map((b,i)=><div className="reading-block" key={b.book+b.chapter+b.start+i}><h4>{b.book} {b.chapter}:{b.start}–{b.end}</h4>{b.verses.map(v=><p key={v.v}><sup>{v.v}</sup>{v.text}</p>)}</div>)}</div><Reflection label="WHAT DID I LEARN?" value={notes.learn} save={v=>save('learn',v)}/><div className="reflection-grid"><Reflection label="WHAT STOOD OUT?" value={notes.stood} save={v=>save('stood',v)}/><Reflection label="HOW DOES THIS APPLY?" value={notes.apply} save={v=>save('apply',v)}/></div><div className="reflection-grid"><Reflection label="KEY POINT" value={notes.key} save={v=>save('key',v)}/><Reflection label="MY PRAYER" value={notes.prayer} save={v=>save('prayer',v)}/></div></article></section>}

const Reflection=({label,value,save})=><div className="reflection"><label>{label}</label><textarea value={value||''} onChange={e=>save(e.target.value)} placeholder="Write here…"/></div>;

function Bible({book,chapter,setBook,setChapter,data,verses,books,open,saved,setSaved,marks,setMarks,notes,saveNote,setScreen,loading,load}){const idx=books.findIndex(b=>b[0]===book);const max=books[idx]?.[1]||1;const jump=(c)=>{setChapter(c);window.scrollTo({top:0,behavior:'smooth'})};const prev=chapter>1?()=>jump(chapter-1):idx>0?()=>open(books[idx-1][0],books[idx-1][1]):null;const next=chapter<max?()=>jump(chapter+1):idx<books.length-1?()=>open(books[idx+1][0],1):null;return <section className="content-page"><div className="section-head"><div><p className="eyebrow">FULL BIBLE LIBRARY · WEB</p><h2>{book} {chapter}</h2><p className="muted">HOME → BIBLE → {book} → CHAPTER {chapter}</p></div><button className="secondary" onClick={()=>setScreen('home')}>⌂ Home</button></div><div className="bible-layout"><aside className="book-list"><h4>OLD & NEW TESTAMENT · 66 BOOKS</h4>{books.map((b,i)=><button className={b[0]===book?'book active':'book'} key={b[0]} onClick={()=>open(b[0],1)}>{i===39&&<span className="testament-divider">NEW TESTAMENT</span>}{b[0]}</button>)}</aside><article className="bible-reader"><div className="reader-toolbar"><select value={chapter} onChange={e=>jump(+e.target.value)}>{Array.from({length:max},(_,i)=><option key={i+1} value={i+1}>Chapter {i+1}</option>)}</select><div><button disabled={!prev} onClick={prev}>← Prev</button><button disabled={!next} onClick={next}>Next →</button></div></div><h3>{book} {chapter}</h3>{loading&&!data?<p className="muted">Loading Scripture…</p>:verses.map(v=>{let r=book+' '+chapter+':'+v.v;return <div className={'verse '+(marks[r]||'')} key={v.v}><button className="verse-no" onClick={()=>setSaved(x=>x.includes(r)?x.filter(y=>y!==r):[...x,r])}>{v.v}</button><span>{v.text}</span><div className="verse-tools"><button onClick={()=>setMarks(x=>({...x,[r]:x[r]==='yellow'?'':'yellow'}))}>Highlight</button><button onClick={()=>setMarks(x=>({...x,[r]:x[r]==='lavender'?'':'lavender'}))}>Lavender</button><button onClick={()=>setSaved(x=>x.includes(r)?x.filter(y=>y!==r):[...x,r])}>{saved.includes(r)?'★ Saved':'☆ Save'}</button></div></div>})}<div className="reader-actions"><button onClick={()=>setScreen('journal')}>✎ Journal about this chapter</button><button onClick={()=>setScreen('bookmarks')}>★ My bookmarks</button><button onClick={()=>setScreen('home')}>⌂ Home</button></div><div className="chapter-journal"><p className="eyebrow">JOURNAL ABOUT THIS CHAPTER</p>{['learn','spoke','apply','prayer'].map((f,i)=><Reflection key={f} label={['WHAT DID I LEARN?','WHAT SPOKE TO ME?','QUESTIONS / APPLICATION','PRAYER'][i]} value={notes[f]} save={v=>saveNote(f,v)}/>)}</div></article></div></section>}

function Topics({topic,results,show,open,setTopic,loading}){return <section className="content-page"><div className="section-head"><div><p className="eyebrow">STUDY BY SUBJECT</p><h2>Topics</h2><p className="muted">Curated starting points. Each reference opens the exact Bible chapter.</p></div></div>{!topic?<div className="topic-grid">{TOPICS.map(t=><button key={t} onClick={()=>show(t)}>{t}<span>→</span></button>)}</div>:<article className="journal-card topic-page"><button className="back" onClick={()=>setTopic(null)}>← All topics</button><p className="eyebrow">TOPIC</p><h3>{topic}</h3>{loading?<p className="muted">Loading topic Scriptures…</p>:<div className="topic-results">{results.map((r,i)=><button key={i} onClick={()=>open(r.book,r.chapter)}><b>{r.ref}</b><span>{r.text}</span></button>)}</div>}</article>}</section>}

function Journal({prayers,setPrayers}){const[f,setF]=useState({title:'',prayer:'',category:'Personal',status:'Active'});const add=()=>{if(!f.prayer.trim())return;setPrayers(x=>[{...f,date:new Date().toISOString().slice(0,10),id:Date.now()},...x]);setF({title:'',prayer:'',category:'Personal',status:'Active'})};return <section className="content-page"><div className="section-head"><div><p className="eyebrow">YOUR WRITING SPACE</p><h2>Prayer Journal</h2></div></div><div className="journal-layout"><article className="journal-card"><p className="eyebrow">NEW PRAYER</p><input className="form-input" value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="Prayer title"/><textarea className="prayer-input" value={f.prayer} onChange={e=>setF({...f,prayer:e.target.value})} placeholder="Write your prayer…"/><div className="form-row"><select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{['Personal','Family','Health','Career','Ministry','Finances','Relationships','Spiritual Growth','Other'].map(x=><option key={x}>{x}</option>)}</select><select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option>Active</option><option>Answered</option></select><button className="primary" onClick={add}>Save prayer</button></div></article><aside className="side-card"><p className="eyebrow">SAVED PRAYERS</p>{prayers.length===0&&<p className="muted">Your saved prayers will appear here.</p>}{prayers.map(p=><div className="saved-item" key={p.id}><b>{p.title||'Prayer'}</b><small>{p.date} · {p.category} · {p.status}</small><p>{p.prayer}</p></div>)}</aside></div></section>}

function Bookmarks({saved,marks,open}){const items=saved.map(r=>({r,type:'Saved'}));const highlights=Object.entries(marks).filter(([,v])=>v).map(([r,v])=>({r,type:v}));return <section className="content-page"><div className="section-head"><div><p className="eyebrow">YOUR SCRIPTURE COLLECTION</p><h2>Bookmarks & highlights</h2></div></div>{!items.length&&!highlights.length?<div className="journal-card empty-state"><h3>Nothing saved yet</h3><p className="muted">Use Save or Highlight while reading the Bible.</p><button className="primary" onClick={()=>open('Genesis',1)}>Open Genesis</button></div>:<div className="bookmark-grid">{[...items,...highlights].map((x,i)=>{let p=refs(x.r)[0];return <button key={i} onClick={()=>p&&open(p.book,p.chapter)}><b>{x.r}</b><span>{x.type}</span></button>})}</div>}</section>}

function Search({q,setQ,search,results,open,loading}){return <section className="content-page"><div className="section-head"><div><p className="eyebrow">SEARCH SCRIPTURE</p><h2>Find a verse</h2><p className="muted">Search a word, phrase, or exact reference such as John 3:16.</p></div></div><div className="search-box"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Word, phrase, or John 3:16"/><button className="primary" onClick={search}>Search</button></div>{loading&&<p className="muted">Searching the Bible…</p>}{!loading&&!results.length&&q&&<p className="muted">No matches found.</p>}<div className="results">{results.map((r,i)=><button key={i} onClick={()=>open(r.book,r.chapter)}><b>{r.ref}</b><span>{r.text}</span></button>)}</div></section>}

createRoot(document.getElementById('root')).render(<App/>);
